"""added gig list

Revision ID: 03480c6ff048
Revises: f2907b54f0d7
Create Date: 2024-11-26 17:53:54.858964

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03480c6ff048"
down_revision: Union[str, None] = "f2907b54f0d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_gig_lists",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("long", sa.Float(), nullable=True),
        sa.Column("wage_requested", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_looking_for", sa.Boolean(), nullable=False),
        sa.Column("is_performer", sa.Boolean(), nullable=False),
        sa.Column("add_call_to_action", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_gig_lists_created_at"),
        "gigger_gig_lists",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gigger_gig_lists_uuid"), "gigger_gig_lists", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_gig_list_hashtags",
        sa.Column("gig_list_uuid", sa.Uuid(), nullable=False),
        sa.Column("hashtag_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gig_list_uuid"], ["gigger_gig_lists.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["hashtag_uuid"], ["gigger_hashtags.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("gig_list_uuid", "hashtag_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_gig_list_hashtags")
    op.drop_index(op.f("ix_gigger_gig_lists_uuid"), table_name="gigger_gig_lists")
    op.drop_index(op.f("ix_gigger_gig_lists_created_at"), table_name="gigger_gig_lists")
    op.drop_table("gigger_gig_lists")
    # ### end Alembic commands ###
