"""fixed call to action miss place

Revision ID: 055d420d3636
Revises: fa59a9f55032
Create Date: 2025-01-17 15:29:59.652879

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "055d420d3636"
down_revision: Union[str, None] = "fa59a9f55032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_gig_list_stars", sa.Column("gig_list_uuid", sa.Uuid(), nullable=False)
    )
    op.drop_constraint(
        "gigger_gig_list_stars_profile_uuid_fkey",
        "gigger_gig_list_stars",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "gigger_gig_list_stars",
        "gigger_gig_lists",
        ["gig_list_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_gig_list_stars", "profile_uuid")
    op.add_column(
        "gigger_gig_lists",
        sa.Column(
            "call_to_action",
            sa.JSON(),
            nullable=False,
            default={"name": None, "value": None},
        ),
    )
    op.add_column(
        "gigger_post_viewers", sa.Column("post_uuid", sa.Uuid(), nullable=False)
    )
    op.drop_constraint(
        "gigger_post_viewers_profile_uuid_fkey",
        "gigger_post_viewers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "gigger_post_viewers",
        "gigger_posts",
        ["post_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_post_viewers", "profile_uuid")
    op.add_column("gigger_sup_likes", sa.Column("sup_uuid", sa.Uuid(), nullable=False))
    op.drop_constraint(
        "gigger_sup_likes_profile_uuid_fkey", "gigger_sup_likes", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "gigger_sup_likes",
        "gigger_sup_posts",
        ["sup_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_sup_likes", "profile_uuid")
    op.drop_column("gigger_sup_posts", "call_to_action")
    op.add_column("gigger_sup_shares", sa.Column("sup_uuid", sa.Uuid(), nullable=False))
    op.drop_constraint(
        "gigger_sup_shares_profile_uuid_fkey", "gigger_sup_shares", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "gigger_sup_shares",
        "gigger_sup_posts",
        ["sup_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_sup_shares", "profile_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_sup_shares",
        sa.Column("profile_uuid", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("", "gigger_sup_shares", type_="foreignkey")
    op.create_foreign_key(
        "gigger_sup_shares_profile_uuid_fkey",
        "gigger_sup_shares",
        "gigger_profiles",
        ["profile_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_sup_shares", "sup_uuid")
    op.add_column(
        "gigger_sup_posts",
        sa.Column(
            "call_to_action",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
            default={"name": None, "value": None},
        ),
    )
    op.add_column(
        "gigger_sup_likes",
        sa.Column("profile_uuid", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("", "gigger_sup_likes", type_="foreignkey")
    op.create_foreign_key(
        "gigger_sup_likes_profile_uuid_fkey",
        "gigger_sup_likes",
        "gigger_profiles",
        ["profile_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_sup_likes", "sup_uuid")
    op.add_column(
        "gigger_post_viewers",
        sa.Column("profile_uuid", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("", "gigger_post_viewers", type_="foreignkey")
    op.create_foreign_key(
        "gigger_post_viewers_profile_uuid_fkey",
        "gigger_post_viewers",
        "gigger_profiles",
        ["profile_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_post_viewers", "post_uuid")
    op.drop_column("gigger_gig_lists", "call_to_action")
    op.add_column(
        "gigger_gig_list_stars",
        sa.Column("profile_uuid", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("", "gigger_gig_list_stars", type_="foreignkey")
    op.create_foreign_key(
        "gigger_gig_list_stars_profile_uuid_fkey",
        "gigger_gig_list_stars",
        "gigger_profiles",
        ["profile_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_column("gigger_gig_list_stars", "gig_list_uuid")
    # ### end Alembic commands ###
