"""post added

Revision ID: 213f4bc5204e
Revises: f113b7a10e8e
Create Date: 2024-11-13 15:34:37.808412

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "213f4bc5204e"
down_revision: Union[str, None] = "f113b7a10e8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_hashtags",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_gigger_hashtags_uuid"), "gigger_hashtags", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_posts",
        sa.Column("post_title", sa.String(), nullable=False),
        sa.Column("caption", sa.String(), nullable=False),
        sa.Column("music_title", sa.String(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("is_membership_only", sa.Boolean(), nullable=False),
        sa.Column("is_only_for_followers", sa.Boolean(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.Column("thumbnail_url", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("long", sa.Float(), nullable=True),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gigger_posts_uuid"), "gigger_posts", ["uuid"], unique=True)
    op.create_table(
        "gigger_post_hashtags",
        sa.Column("post_uuid", sa.Uuid(), nullable=False),
        sa.Column("hashtag_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hashtag_uuid"], ["gigger_hashtags.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["post_uuid"], ["gigger_posts.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_uuid", "hashtag_uuid"),
    )
    op.create_table(
        "gigger_post_mentions",
        sa.Column("post_uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_uuid"], ["gigger_posts.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_uuid", "profile_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_post_mentions")
    op.drop_table("gigger_post_hashtags")
    op.drop_index(op.f("ix_gigger_posts_uuid"), table_name="gigger_posts")
    op.drop_table("gigger_posts")
    op.drop_index(op.f("ix_gigger_hashtags_uuid"), table_name="gigger_hashtags")
    op.drop_table("gigger_hashtags")
    # ### end Alembic commands ###
