"""added event table

Revision ID: 24d96cc724ff
Revises: bcd2795d4877
Create Date: 2025-03-11 11:51:31.916073

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24d96cc724ff"
down_revision: Union[str, None] = "bcd2795d4877"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_events",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("genre", sa.String(), nullable=False),
        sa.Column("thumbnail_url", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lon", sa.Float(), nullable=True),
        sa.Column("online_event_link", sa.String(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("ticket_price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "call_to_action",
            sa.JSON(),
            server_default=sa.text('\'{"name": null, "value": null}\''),
            nullable=False,
        ),
        sa.Column("is_membership_content", sa.Boolean(), nullable=False),
        sa.Column("contacts", sa.JSON(), server_default=sa.text("NULL"), nullable=True),
        sa.Column(
            "social_links", sa.JSON(), server_default=sa.text("NULL"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_events_created_at"),
        "gigger_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gigger_events_uuid"), "gigger_events", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_events_line_ups_n_performers",
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "is_accepted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_uuid"], ["gigger_events.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_events_line_ups_n_performers_created_at"),
        "gigger_events_line_ups_n_performers",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_gigger_events_line_ups_n_performers_created_at"),
        table_name="gigger_events_line_ups_n_performers",
    )
    op.drop_table("gigger_events_line_ups_n_performers")
    op.drop_index(op.f("ix_gigger_events_uuid"), table_name="gigger_events")
    op.drop_index(op.f("ix_gigger_events_created_at"), table_name="gigger_events")
    op.drop_table("gigger_events")
    # ### end Alembic commands ###
