"""added new many to many table for events

Revision ID: 2a17381605b7
Revises: 9ec59d7690f2
Create Date: 2025-03-20 09:45:54.882630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a17381605b7"
down_revision: Union[str, None] = "9ec59d7690f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_event_likes",
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column("liker_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_uuid"], ["gigger_events.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["liker_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_uuid", "liker_uuid"),
    )
    op.create_table(
        "gigger_event_responses",
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column("responder_uuid", sa.Uuid(), nullable=False),
        sa.Column("response", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_uuid"], ["gigger_events.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["responder_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_uuid", "responder_uuid"),
    )
    op.create_index(
        op.f("ix_gigger_event_responses_event_uuid"),
        "gigger_event_responses",
        ["event_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gigger_event_responses_response"),
        "gigger_event_responses",
        ["response"],
        unique=False,
    )
    op.create_table(
        "gigger_event_views",
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column("viewer_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_uuid"], ["gigger_events.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["viewer_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_uuid", "viewer_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_event_views")
    op.drop_index(
        op.f("ix_gigger_event_responses_response"), table_name="gigger_event_responses"
    )
    op.drop_index(
        op.f("ix_gigger_event_responses_event_uuid"),
        table_name="gigger_event_responses",
    )
    op.drop_table("gigger_event_responses")
    op.drop_table("gigger_event_likes")
    # ### end Alembic commands ###
