"""added private mode in profile

Revision ID: 2c6caef885f0
Revises: 5c3e5667f481
Create Date: 2025-01-28 09:30:35.056580

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c6caef885f0"
down_revision: Union[str, None] = "5c3e5667f481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_profiles",
        sa.Column(
            "is_private_profile",
            sa.Boolean(),
            nullable=False,
            default=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_profiles", "is_private_profile")
    # ### end Alembic commands ###
