"""changed device token uniq

Revision ID: 2e3b39634931
Revises: 976457772e88
Create Date: 2025-01-06 17:04:09.630582

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e3b39634931"
down_revision: Union[str, None] = "976457772e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_fcm_token_device_uuid", "gigger_device_tokens", type_="unique"
    )
    op.create_unique_constraint(
        "unique_fcm_token_device_uuid",
        "gigger_device_tokens",
        ["device_uuid", "profile_uuid"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_fcm_token_device_uuid", "gigger_device_tokens", type_="unique"
    )
    op.create_unique_constraint(
        "unique_fcm_token_device_uuid",
        "gigger_device_tokens",
        ["fcm_token", "device_uuid", "profile_uuid"],
    )
    # ### end Alembic commands ###
