"""removed migration error

Revision ID: 2f5809092e40
Revises: f7dfdbfdb369
Create Date: 2025-01-16 12:52:28.168878

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f5809092e40"
down_revision: Union[str, None] = "f7dfdbfdb369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_sup_posts", "is_already_seen")
    op.drop_column("gigger_sup_posts", "call_to_action")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_sup_posts",
        sa.Column(
            "call_to_action",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
            default={"name": None, "value": None},
        ),
    )
    op.add_column(
        "gigger_sup_posts",
        sa.Column(
            "is_already_seen",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            default=False,
        ),
    )

    # ### end Alembic commands ###
