"""post added index

Revision ID: 38a80d35c553
Revises: 785279912332
Create Date: 2024-12-10 19:35:08.814848

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38a80d35c553"
down_revision: Union[str, None] = "785279912332"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_posts", sa.Column("position_on_fab_nine", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_posts", "position_on_fab_nine")
    # ### end Alembic commands ###
