"""added missing datemixin

Revision ID: 44212dadd826
Revises: 5fd4764c833c
Create Date: 2024-12-06 21:27:40.118459

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44212dadd826"
down_revision: Union[str, None] = "5fd4764c833c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add `created_at` and `updated_at` with a default value for existing rows
    op.add_column(
        "gigger_posts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.add_column(
        "gigger_posts",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        op.f("ix_gigger_posts_created_at"), "gigger_posts", ["created_at"], unique=False
    )

    op.add_column(
        "gigger_profiles",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.add_column(
        "gigger_profiles",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        op.f("ix_gigger_profiles_created_at"),
        "gigger_profiles",
        ["created_at"],
        unique=False,
    )

    # Optionally remove the default after the migration
    op.alter_column("gigger_posts", "created_at", server_default=None)
    op.alter_column("gigger_posts", "updated_at", server_default=None)
    op.alter_column("gigger_profiles", "created_at", server_default=None)
    op.alter_column("gigger_profiles", "updated_at", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gigger_profiles_created_at"), table_name="gigger_profiles")
    op.drop_column("gigger_profiles", "updated_at")
    op.drop_column("gigger_profiles", "created_at")
    op.drop_index(op.f("ix_gigger_posts_created_at"), table_name="gigger_posts")
    op.drop_column("gigger_posts", "updated_at")
    op.drop_column("gigger_posts", "created_at")
    # ### end Alembic commands ###
