"""updated giglist

Revision ID: 513c01a595d6
Revises: f5d187d15897
Create Date: 2024-12-19 10:44:39.830651

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "513c01a595d6"
down_revision: Union[str, None] = "f5d187d15897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_gig_lists", sa.Column("image_url_1", sa.String(), nullable=True)
    )
    op.add_column(
        "gigger_gig_lists", sa.Column("image_url_2", sa.String(), nullable=True)
    )
    op.add_column(
        "gigger_gig_lists", sa.Column("image_url_3", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_gig_lists", "image_url_3")
    op.drop_column("gigger_gig_lists", "image_url_2")
    op.drop_column("gigger_gig_lists", "image_url_1")
    # ### end Alembic commands ###
