"""feat model changed

Revision ID: 5899cd8c2e28
Revises: 8abe7a254281
Create Date: 2025-01-23 19:13:54.846018

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5899cd8c2e28"
down_revision: Union[str, None] = "8abe7a254281"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gigger_posts", sa.Column("view_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_posts", "view_count")
    # ### end Alembic commands ###
