"""sup created from enum changed

Revision ID: 5c3e5667f481
Revises: 5899cd8c2e28
Create Date: 2025-01-27 10:42:26.082159

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c3e5667f481"
down_revision: Union[str, None] = "5899cd8c2e28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE supcreatedfromenum ADD VALUE 'EVENT'")
    op.execute("ALTER TYPE supcreatedfromenum ADD VALUE 'PRO_SERVICE'")
    op.execute("ALTER TYPE supcreatedfromenum ADD VALUE 'CAMPAIGN'")
    op.execute("ALTER TYPE supcreatedfromenum ADD VALUE 'MEMBERSHIP'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE supcreatedfromenum_old AS ENUM('POST', 'GIG_LIST', 'ARTIST', 'NONE')"
    )
    op.execute(
        "ALTER TABLE gigger_sup_posts ALTER COLUMN create_from TYPE supcreatedfromenum_old USING create_from::text::supcreatedfromenum_old"
    )
    op.execute("DROP TYPE supcreatedfromenum")
    op.execute("ALTER TYPE supcreatedfromenum_old RENAME TO supcreatedfromenum")
    # ### end Alembic commands ###
