"""fix gig list

Revision ID: 5fd4764c833c
Revises: 03480c6ff048
Create Date: 2024-12-03 11:34:36.965718

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fd4764c833c"
down_revision: Union[str, None] = "03480c6ff048"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_gig_lists", sa.Column("thumbnail_url", sa.String(), nullable=False)
    )
    op.add_column(
        "gigger_gig_lists", sa.Column("video_url", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_gig_lists", "video_url")
    op.drop_column("gigger_gig_lists", "thumbnail_url")
    # ### end Alembic commands ###
