"""added follower logic

Revision ID: 785279912332
Revises: 44212dadd826
Create Date: 2024-12-10 11:27:34.438086

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "785279912332"
down_revision: Union[str, None] = "44212dadd826"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_follower_requests",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("follower_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "follower_uuid"),
    )
    op.create_table(
        "gigger_profile_followers",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("follower_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["follower_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "follower_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_profile_followers")
    op.drop_table("gigger_follower_requests")
    # ### end Alembic commands ###
