"""changed notification column name

Revision ID: 7ef8ce8d9ce2
Revises: 2c6caef885f0
Create Date: 2025-01-28 16:00:15.826062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ef8ce8d9ce2"
down_revision: Union[str, None] = "2c6caef885f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_notifications",
        sa.Column("notification_type", sa.SmallInteger(), nullable=False),
    )
    op.drop_column("gigger_notifications", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_notifications",
        sa.Column("type", sa.SMALLINT(), autoincrement=False, nullable=False),
    )
    op.drop_column("gigger_notifications", "notification_type")
    # ### end Alembic commands ###
