"""fixed migration error

Revision ID: 8abe7a254281
Revises: 055d420d3636
Create Date: 2025-01-17 15:43:05.450439

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8abe7a254281"
down_revision: Union[str, None] = "055d420d3636"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
