"""update giglist

Revision ID: 8cb12ee8c3a6
Revises: 513c01a595d6
Create Date: 2024-12-23 21:04:26.318057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cb12ee8c3a6"
down_revision: Union[str, None] = "513c01a595d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_gig_lists", sa.Column("gig_list_media", sa.JSON(), nullable=False)
    )
    op.drop_column("gigger_gig_lists", "image_url_3")
    op.drop_column("gigger_gig_lists", "image_url_1")
    op.drop_column("gigger_gig_lists", "video_url")
    op.drop_column("gigger_gig_lists", "image_url_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_gig_lists",
        sa.Column("image_url_2", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gigger_gig_lists",
        sa.Column("video_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "gigger_gig_lists",
        sa.Column("image_url_1", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gigger_gig_lists",
        sa.Column("image_url_3", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("gigger_gig_lists", "gig_list_media")
    # ### end Alembic commands ###
