"""added device token

Revision ID: 976457772e88
Revises: 8cb12ee8c3a6
Create Date: 2025-01-02 14:05:57.624150

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "976457772e88"
down_revision: Union[str, None] = "8cb12ee8c3a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_device_tokens",
        sa.Column("fcm_token", sa.String(), nullable=False),
        sa.Column("device_uuid", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fcm_token",
            "device_uuid",
            "profile_uuid",
            name="unique_fcm_token_device_uuid",
        ),
    )
    op.create_index(
        op.f("ix_gigger_device_tokens_created_at"),
        "gigger_device_tokens",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_gigger_device_tokens_created_at"), table_name="gigger_device_tokens"
    )
    op.drop_table("gigger_device_tokens")
    # ### end Alembic commands ###
