"""added sup

Revision ID: 9d5f47e17072
Revises: dbe4cd6f03c9
Create Date: 2024-11-21 21:10:55.361971

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d5f47e17072"
down_revision: Union[str, None] = "dbe4cd6f03c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_sup_posts",
        sa.Column("caption", sa.String(length=150), nullable=False),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.Column("thumbnail_url", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("long", sa.Float(), nullable=True),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("is_membership_only", sa.Boolean(), nullable=False),
        sa.Column("is_only_for_followers", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_sup_posts_created_at"),
        "gigger_sup_posts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gigger_sup_posts_uuid"), "gigger_sup_posts", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_sup_hashtags",
        sa.Column("sub_uuid", sa.Uuid(), nullable=False),
        sa.Column("hashtag_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hashtag_uuid"], ["gigger_hashtags.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sub_uuid"], ["gigger_sup_posts.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sub_uuid", "hashtag_uuid"),
    )
    op.create_table(
        "gigger_sup_mentions",
        sa.Column("sub_uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sub_uuid"], ["gigger_sup_posts.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sub_uuid", "profile_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_sup_mentions")
    op.drop_table("gigger_sup_hashtags")
    op.drop_index(op.f("ix_gigger_sup_posts_uuid"), table_name="gigger_sup_posts")
    op.drop_index(op.f("ix_gigger_sup_posts_created_at"), table_name="gigger_sup_posts")
    op.drop_table("gigger_sup_posts")
    # ### end Alembic commands ###
