"""updated post like table

Revision ID: bcd2795d4877
Revises: bec2bf89776f
Create Date: 2025-02-19 14:12:05.824847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcd2795d4877"
down_revision: Union[str, None] = "bec2bf89776f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_post_likers",
        sa.Column("post_uuid", sa.Uuid(), nullable=False),
        sa.Column("liker_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["liker_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["post_uuid"], ["gigger_posts.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_uuid", "liker_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_post_likers")
    # ### end Alembic commands ###
