"""added sup view , gig_list like

Revision ID: bec2bf89776f
Revises: 7ef8ce8d9ce2
Create Date: 2025-02-11 12:35:20.449347

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bec2bf89776f"
down_revision: Union[str, None] = "7ef8ce8d9ce2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_gig_list_likes",
        sa.Column("gig_list_uuid", sa.Uuid(), nullable=False),
        sa.Column("liker_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gig_list_uuid"], ["gigger_gig_lists.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["liker_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("gig_list_uuid", "liker_uuid"),
    )
    op.create_table(
        "gigger_sup_view",
        sa.Column("sup_uuid", sa.Uuid(), nullable=False),
        sa.Column("viewer_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sup_uuid"], ["gigger_sup_posts.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["viewer_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("sup_uuid", "viewer_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_sup_view")
    op.drop_table("gigger_gig_list_likes")
    # ### end Alembic commands ###
