"""updated event table

Revision ID: d743cb5f7337
Revises: e9fd696c7b5f
Create Date: 2025-03-18 10:30:07.911524

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d743cb5f7337"
down_revision: Union[str, None] = "e9fd696c7b5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_event_hashtags",
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column("hashtag_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_uuid"], ["gigger_events.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["hashtag_uuid"], ["gigger_hashtags.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_uuid", "hashtag_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gigger_event_hashtags")
    # ### end Alembic commands ###
