"""added view and like tables and updated sups

Revision ID: d9b94b9e50e9
Revises: 2e3b39634931
Create Date: 2025-01-16 11:58:53.795587

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9b94b9e50e9"
down_revision: Union[str, None] = "2e3b39634931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_gig_list_stars",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("viewer_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["viewer_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "viewer_uuid"),
    )
    op.create_table(
        "gigger_notifications",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("type", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_notifications_created_at"),
        "gigger_notifications",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "gigger_post_viewers",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("viewer_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["viewer_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "viewer_uuid"),
    )
    op.create_table(
        "gigger_profile_likes",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("liker_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["liker_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "liker_uuid"),
    )
    op.create_table(
        "gigger_profile_viewers",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("viewer_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["viewer_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "viewer_uuid"),
    )
    op.create_table(
        "gigger_sup_likes",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("viewer_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["viewer_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "viewer_uuid"),
    )
    op.create_table(
        "gigger_sup_shares",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("viewer_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["viewer_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "viewer_uuid"),
    )
    op.add_column(
        "gigger_sup_posts",
        sa.Column("is_already_seen", sa.Boolean(), nullable=False, default=False),
    )
    op.add_column(
        "gigger_sup_posts",
        sa.Column(
            "call_to_action",
            sa.JSON(),
            nullable=False,
            default={"name": None, "value": None},
        ),
    )
    create_from = sa.Enum(
        "POST", "GIG_LIST", "ARTIST", "NONE", name="supcreatedfromenum"
    )
    create_from.create(op.get_bind())
    op.add_column(
        "gigger_sup_posts",
        sa.Column(
            "create_from",
            create_from,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_sup_posts", "create_from")
    op.drop_column("gigger_sup_posts", "call_to_action")
    op.drop_column("gigger_sup_posts", "is_already_seen")
    op.drop_table("gigger_sup_shares")
    op.drop_table("gigger_sup_likes")
    op.drop_table("gigger_profile_viewers")
    op.drop_table("gigger_profile_likes")
    op.drop_table("gigger_post_viewers")
    op.drop_index(
        op.f("ix_gigger_notifications_created_at"), table_name="gigger_notifications"
    )
    op.drop_table("gigger_notifications")
    op.drop_table("gigger_gig_list_stars")
    # ### end Alembic commands ###
