"""lastest stable

Revision ID: dae0aec4c138
Revises:
Create Date: 2024-11-01 23:01:32.122854

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dae0aec4c138"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_accounts",
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_developer", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        op.f("ix_gigger_accounts_created_at"),
        "gigger_accounts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gigger_accounts_uuid"), "gigger_accounts", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_blocked_refresh_tokens",
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token"),
    )
    op.create_index(
        op.f("ix_gigger_blocked_refresh_tokens_uuid"),
        "gigger_blocked_refresh_tokens",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "gigger_interests",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_gigger_interests_category"),
        "gigger_interests",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gigger_interests_uuid"), "gigger_interests", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_my_services",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_gigger_my_services_uuid"), "gigger_my_services", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_server_config",
        sa.Column("cdn_url", sa.String(length=256), nullable=True),
        sa.Column("base_url", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_server_config_created_at"),
        "gigger_server_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "gigger_skills",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_gigger_skills_uuid"), "gigger_skills", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_email_verifications",
        sa.Column("opt", sa.String(length=6), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("dev_mode", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("account_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_uuid"], ["gigger_accounts.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opt"),
    )
    op.create_index(
        op.f("ix_gigger_email_verifications_uuid"),
        "gigger_email_verifications",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "gigger_profiles",
        sa.Column("account_uuid", sa.Uuid(), nullable=False),
        sa.Column("cover_media", sa.String(), nullable=False),
        sa.Column("avatar_media", sa.String(), nullable=False),
        sa.Column("bio", sa.String(), nullable=False),
        sa.Column("availability_status", sa.Boolean(), nullable=False),
        sa.Column("custom_phrase", sa.String(), nullable=False),
        sa.Column("closing_message", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_uuid"], ["gigger_accounts.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_profiles_uuid"), "gigger_profiles", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_availability",
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_availability_uuid"),
        "gigger_availability",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "gigger_contacts",
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_contacts_uuid"), "gigger_contacts", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_education",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_education_uuid"), "gigger_education", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_experiences",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_experiences_uuid"), "gigger_experiences", ["uuid"], unique=True
    )
    op.create_table(
        "gigger_profile_interests",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("interest_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_uuid"], ["gigger_interests.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "interest_uuid"),
    )
    op.create_table(
        "gigger_profile_locations",
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_profile_locations_uuid"),
        "gigger_profile_locations",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "gigger_profile_services",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("service_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["service_uuid"], ["gigger_my_services.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "service_uuid"),
    )
    op.create_table(
        "gigger_profile_skills",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("skill_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_uuid"], ["gigger_skills.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("profile_uuid", "skill_uuid"),
    )
    op.create_table(
        "gigger_social_links",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "facebook",
                "x",
                "instagram",
                "linkedin",
                "github",
                "discord",
                "telegram",
                "tiktok",
                "youtube",
                "twitch",
                name="sociallinks",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_social_links_uuid"),
        "gigger_social_links",
        ["uuid"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gigger_social_links_uuid"), table_name="gigger_social_links")
    op.drop_table("gigger_social_links")
    op.drop_table("gigger_profile_skills")
    op.drop_table("gigger_profile_services")
    op.drop_index(
        op.f("ix_gigger_profile_locations_uuid"), table_name="gigger_profile_locations"
    )
    op.drop_table("gigger_profile_locations")
    op.drop_table("gigger_profile_interests")
    op.drop_index(op.f("ix_gigger_experiences_uuid"), table_name="gigger_experiences")
    op.drop_table("gigger_experiences")
    op.drop_index(op.f("ix_gigger_education_uuid"), table_name="gigger_education")
    op.drop_table("gigger_education")
    op.drop_index(op.f("ix_gigger_contacts_uuid"), table_name="gigger_contacts")
    op.drop_table("gigger_contacts")
    op.drop_index(op.f("ix_gigger_availability_uuid"), table_name="gigger_availability")
    op.drop_table("gigger_availability")
    op.drop_index(op.f("ix_gigger_profiles_uuid"), table_name="gigger_profiles")
    op.drop_table("gigger_profiles")
    op.drop_index(
        op.f("ix_gigger_email_verifications_uuid"),
        table_name="gigger_email_verifications",
    )
    op.drop_table("gigger_email_verifications")
    op.drop_index(op.f("ix_gigger_skills_uuid"), table_name="gigger_skills")
    op.drop_table("gigger_skills")
    op.drop_index(
        op.f("ix_gigger_server_config_created_at"), table_name="gigger_server_config"
    )
    op.drop_table("gigger_server_config")
    op.drop_index(op.f("ix_gigger_my_services_uuid"), table_name="gigger_my_services")
    op.drop_table("gigger_my_services")
    op.drop_index(op.f("ix_gigger_interests_uuid"), table_name="gigger_interests")
    op.drop_index(op.f("ix_gigger_interests_category"), table_name="gigger_interests")
    op.drop_table("gigger_interests")
    op.drop_index(
        op.f("ix_gigger_blocked_refresh_tokens_uuid"),
        table_name="gigger_blocked_refresh_tokens",
    )
    op.drop_table("gigger_blocked_refresh_tokens")
    op.drop_index(op.f("ix_gigger_accounts_uuid"), table_name="gigger_accounts")
    op.drop_index(op.f("ix_gigger_accounts_created_at"), table_name="gigger_accounts")
    op.drop_table("gigger_accounts")
    # ### end Alembic commands ###
