"""email verification fix

Revision ID: dbe4cd6f03c9
Revises: 213f4bc5204e
Create Date: 2024-11-14 10:06:20.245474

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbe4cd6f03c9"
down_revision: Union[str, None] = "213f4bc5204e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "gigger_email_verifications_opt_key",
        "gigger_email_verifications",
        type_="unique",
    )
    op.create_unique_constraint(
        "email_dev_mode", "gigger_email_verifications", ["email", "dev_mode", "opt"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email_dev_mode", "gigger_email_verifications", type_="unique")
    op.create_unique_constraint(
        "gigger_email_verifications_opt_key", "gigger_email_verifications", ["opt"]
    )
    # ### end Alembic commands ###
