"""updated event table

Revision ID: e9fd696c7b5f
Revises: 16a989cbba28
Create Date: 2025-03-11 15:36:06.127894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9fd696c7b5f"
down_revision: Union[str, None] = "16a989cbba28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_events", sa.Column("video_or_image_url", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_events", "video_or_image_url")
    # ### end Alembic commands ###
