"""achievemnets table

Revision ID: f113b7a10e8e
Revises: dae0aec4c138
Create Date: 2024-11-04 11:24:47.415029

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f113b7a10e8e"
down_revision: Union[str, None] = "dae0aec4c138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_achievements",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_gigger_achievements_uuid"),
        "gigger_achievements",
        ["uuid"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gigger_achievements_uuid"), table_name="gigger_achievements")
    op.drop_table("gigger_achievements")
    # ### end Alembic commands ###
