"""make profile.account_uuid unique

Revision ID: f2907b54f0d7
Revises: 9d5f47e17072
Create Date: 2024-11-21 22:00:36.892081

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2907b54f0d7"
down_revision: Union[str, None] = "9d5f47e17072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "gigger_profiles", ["account_uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("", "gigger_profiles", type_="unique")
    # ### end Alembic commands ###
