"""added post layout model

Revision ID: f5d187d15897
Revises: 567a44e6d735
Create Date: 2024-12-10 21:51:09.855647

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5d187d15897"
down_revision: Union[str, None] = "567a44e6d735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gigger_post_layouts",
        sa.Column("layout", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"], ["gigger_profiles.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gigger_post_layouts_uuid"),
        "gigger_post_layouts",
        ["uuid"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gigger_post_layouts_uuid"), table_name="gigger_post_layouts")
    op.drop_table("gigger_post_layouts")
    # ### end Alembic commands ###
