"""fixed sup migration

Revision ID: f7dfdbfdb369
Revises: d9b94b9e50e9
Create Date: 2025-01-16 12:49:13.917344

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f7dfdbfdb369"
down_revision: Union[str, None] = "d9b94b9e50e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
