"""added removed one back

Revision ID: fa59a9f55032
Revises: 2f5809092e40
Create Date: 2025-01-16 12:52:51.464266

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa59a9f55032"
down_revision: Union[str, None] = "2f5809092e40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gigger_sup_posts", sa.Column("is_already_seen", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "gigger_sup_posts", sa.Column("call_to_action", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gigger_sup_posts", "call_to_action")
    op.drop_column("gigger_sup_posts", "is_already_seen")
    # ### end Alembic commands ###
